runtime: python
env: flex
entrypoint: gunicorn -b :$PORT Splicr:app

runtime_config:
    python_version: 3

env_variables:
    YOUTUBE_KEY: YOUR_YOUTUBE_KEY_HERE

handlers:
- url: /.*
  script: Splicr.app
